### ISSUE TITLE
A bug related to your code -- Conv1d

### ISSUE THREAD

**Issue by markyni** [chenpengseu/SDOAnet#1]
Bonjour ! When trying to run your code with torch 1.11, the following error message is found
`Traceback (most recent call last):
  File "/Users/huangxinyue/Desktop/research/DL/SDOAnet-main/SDOAnet-main/main.py", line 107, in <module>
    output_net = net(noisy_signals).view(test_len, 2, -1)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/huangxinyue/Desktop/research/DL/SDOAnet-main/SDOAnet-main/doasys.py", line 113, in forward
    x = self.mod(x)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 295, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'`

**I am wondering where this bug comes from and whether you have met before. Moreover, could you please provide the packages version requirement for this project. Thanks a lot !**

**Comment by Alwin456** [comment]
Traceback (most recent call last):

  File ~\Downloads\SDOAnet-main\SDOAnet-main\main.py:106 in <module>
    output_net = net(noisy_signals).view(test_len, 2, -1)

  File ~\New folder\lib\site-packages\torch\nn\modules\module.py:889 in _call_impl
    result = self.forward(*input, **kwargs)

  File ~\Downloads\SDOAnet-main\SDOAnet-main\doasys.py:111 in forward
    x = self.mod(x)

  File ~\New folder\lib\site-packages\torch\nn\modules\module.py:889 in _call_impl
    result = self.forward(*input, **kwargs)

  File ~\New folder\lib\site-packages\torch\nn\modules\container.py:119 in forward
    input = module(input)

  File ~\New folder\lib\site-packages\torch\nn\modules\module.py:889 in _call_impl
    result = self.forward(*input, **kwargs)

  File ~\New folder\lib\site-packages\torch\nn\modules\conv.py:263 in forward
    return self._conv_forward(input, self.weight, self.bias)

  File ~\New folder\lib\site-packages\torch\nn\modules\conv.py:256 in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),

  File ~\New folder\lib\site-packages\torch\nn\modules\module.py:947 in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(

AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'

**Hi, I too got the same bug. Kindly provide the packages detail to analyze this code. Thanks in advance.**

**Comment by 1548368419** [comment]
Traceback (most recent call last):
  File "D:\Python\阵列大作业\SDOAnet-main\main.py", line 106, in <module>
    output_net = net(noisy_signals).view(test_len, 2, -1)
  File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\阵列大作业\SDOAnet-main\doasys.py", line 111, in forward
    x = self.mod(x)
  File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\Lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 302, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 295, in _conv_forward
    return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
  File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'
您好，请问您的代码出现了如上的错误，能否请您解决一下，提供一下当时运行时pytorch的版本

**Comment by vink1994** [comment]
> Traceback (most recent call last): File "D:\Python\阵列大作业\SDOAnet-main\main.py", line 106, in output_net = net(noisy_signals).view(test_len, 2, -1) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\阵列大作业\SDOAnet-main\doasys.py", line 111, in forward x = self.mod(x) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\Lib\site-packages\torch\nn\modules\container.py", line 141, in forward input = module(input) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 302, in forward return self._conv_forward(input, self.weight, self.bias) File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 295, in _conv_forward return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode), File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1185, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice' 您好，请问您的代码出现了如上的错误，能否请您解决一下，提供一下当时运行时pytorch的版本



> Bonjour ! When trying to run your code with torch 1.11, the following error message is found `Traceback (most recent call last): File "/Users/huangxinyue/Desktop/research/DL/SDOAnet-main/SDOAnet-main/main.py", line 107, in <module> output_net = net(noisy_signals).view(test_len, 2, -1) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/Users/huangxinyue/Desktop/research/DL/SDOAnet-main/SDOAnet-main/doasys.py", line 113, in forward x = self.mod(x) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward input = module(input) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 302, in forward return self._conv_forward(input, self.weight, self.bias) File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 295, in _conv_forward return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode), File "/Users/huangxinyue/opt/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__ raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'`
> 
> **I am wondering where this bug comes from and whether you have met before. Moreover, could you please provide the packages version requirement for this project. Thanks a lot !**

any update on this error

**Comment by vink1994** [comment]
any update??

**Comment by chenqiangwudi** [comment]
AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'，有人解决这个问题吗

**Comment by iwtbam** [comment]
AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice'

**Comment by prathap24reddy** [comment]
In the CNN network, use padding='same' to resolve the error.

**Comment by woaierxu** [comment]
This may be due to the significant difference between the torch version and the version proposed by the author, so if pretrained weights are loaded during the training process, an error will be reported. On line 66 of train.py, change 'if args. new_train:' to 'if True:' to avoid this error, and then modify the doasoy.py file, the padding parameter of nn.Conv1d function can be set to 'same' to run.

**Comment by cindysummer496** [comment]
Why the RMSE out of the code is so high?

**Comment by cczujay** [comment]
请问doa_method部分在哪可以找到

**Comment by cindysummer496** [comment]
Hi. how you solve the lost "doa_method"? If ignore this, the RMSE become very high.

**Comment by July20011124** [comment]
> Traceback (most recent call last): File "D:\Python\阵列大作业\SDOAnet-main\main.py", line 106, in output_net = net(noisy_signals).view(test_len, 2, -1) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\阵列大作业\SDOAnet-main\doasys.py", line 111, in forward x = self.mod(x) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\Lib\site-packages\torch\nn\modules\container.py", line 141, in forward input = module(input) File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl return forward_call(*input, **kwargs) File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 302, in forward return self._conv_forward(input, self.weight, self.bias) File "D:\Python\Lib\site-packages\torch\nn\modules\conv.py", line 295, in _conv_forward return F.conv1d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode), File "D:\Python\Lib\site-packages\torch\nn\modules\module.py", line 1185, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'Conv1d' object has no attribute '_reversed_padding_repeated_twice' 您好，请问您的代码出现了如上的错误，能否请您解决一下，提供一下当时运行时pytorch的版本

请问您解决这个问题了吗？我也是正在做阵列信号处理大作业。卡在这里了。还有那个doa_method软件包找不到呢

**Comment by cczujay** [comment]
我没有解决这个问题，如果您有方法的话我们可以交流一下
